schema_version = 1
name = "bananagine"
version = "0.6.0"
cells = [
  "../registry-cell/pulp.cell.toml",
  "lua-orchestrator.pulp.cell.toml",
  "../pulp-cell/pulp.cell.toml",
]

[orchestrator]
manifest = "lua-orchestrator.pulp.cell.toml"
script = "bananagine.lua"
sha256 = "d67c9663c8eeff040627992018709aa953fdcfd1b5107ca32462fc3eb22e0d7a"
