schema_version = 1
name = "bananagine"
version = "0.6.0"
cells = [
  "../registry-cell/pulp.cell.toml",
  "../template-catalog-cell/pulp.cell.toml",
  "../worker-cell/pulp.cell.toml",
  "lua-orchestrator.pulp.cell.toml",
  "../pulp-cell/pulp.cell.toml",
]

[[execution_units]]
name = "bananagine-state"
artifact = "../state-cell/pulp.cell.toml"
members = ["bananagine-registry", "bananagine-template-catalog"]

[orchestrator]
manifest = "lua-orchestrator.pulp.cell.toml"
script = "bananagine.lua"
sha256 = "589d23646e47ec72a1864a29d7630a301c735b1f62da8dfd4271016e0f85d550"
