name = "async-http-job"
version = "0.1.0"
wasm = "async-http-job.wasm"
wasm_sha256 = "48a3c34c256c3afe9bec69929d091a47eb7505ba279e9c61c1a929cd39032f9a"

provides = [
  "async-http-job.v1.http.submit",
  "async-http-job.v1.status",
  "async-http-job.v1.cancel",
  "async-http-job.v1.snapshot.export",
  "async-http-job.v1.snapshot.import",
]
consumes = []
depends_on = []
capabilities = ["workers"]
