name = "async-http-job"
version = "0.1.0"
wasm = "async-http-job.wasm"
wasm_sha256 = "71bb484fe6266470fa1d77881c9531cb3288de2ad1b00ab6b92dd5330806ca3d"

provides = [
  "async-http-job.v1.http.submit",
  "async-http-job.v1.status",
  "async-http-job.v1.cancel",
  "async-http-job.v1.snapshot.export",
  "async-http-job.v1.snapshot.import",
]
consumes = []
depends_on = []
capabilities = ["workers"]
